#!/bin/bash

ARGS=
REPO_PATH=
OUT_PATH="./cisa_out"
BUILD_SCRIPT_PATH=

_POS=0
while [[ -n "${1}" ]]; do
  if [[ ${1:0:1} == "-" ]]; then
    _ARGS="${1} ${2}"
    if [[ ${1} == "-x" ]]; then
      BUILD_SCRIPT_PATH=${2}
    elif [[ ${1} == "-o" ]]; then
      CISA_OUT=${2}
      _ARGS=""
    fi
    ARGS="${ARGS} ${_ARGS}"
    shift
    shift
  elif [[ ${_POS} == 0 ]]; then
    REPO_PATH=${1}
    (( _POS = _POS + 1 ))
    shift
  fi
done 

if [[ -z ${REPO_PATH} ]]; then
  echo "error: no repo path specified."
  exit
fi

# TODO: -x

CISA_ROOT=/etc/cisa
CONTAINER_REPO_PATH=/etc/repo
CONTAINER_OUT_PATH=/etc/out

docker run -v $(realpath ${REPO_PATH}):${CONTAINER_REPO_PATH} \
  -v $(realpath ${OUT_PATH}):${CONTAINER_OUT_PATH} cisa:latest \
  ${CISA_ROOT}/cisa/cisa \
  ${CONTAINER_REPO_PATH} ${ARGS} -o ${CONTAINER_OUT_PATH}
