#!/bin/bash

ARGS=
REPO_PATH=
OUT_PATH="./out"

_POS=0
while [[ -n "${1}" ]]; do
  if [[ ${1} == "-x" ]]; then
    echo "error: '-x <reconf_path>' cannot be set for a docker container."
    echo "error: use 'make RECONF=<reconf_path>' instead."
    exit
  elif [[ ${1} == "-o" ]]; then
    CISA_OUT=${2}
    shift
    shift
  elif [[ ${1:0:1} == "-" ]]; then
    ARGS="${ARGS} ${1} ${2}"
    shift
    shift
  elif [[ ${_POS} == 0 ]]; then
    REPO_PATH=${1}
    (( _POS = _POS + 1 ))
    shift
  fi
done 

if [[ -z ${REPO_PATH} ]]; then
  echo "error: no repo path specified."
  exit
elif [[ ! -d ${REPO_PATH} ]]; then
  echo "error: wrong repo path."
  exit
fi

CISA_ROOT=/etc/cisa
CONTAINER_REPO_PATH=/etc/repo
CONTAINER_OUT_PATH=/etc/out
CONTAINER_RECONF_PATH=/etc/.proj.reconf

mkdir -p ${OUT_PATH}
docker run --rm -t --user ${USER} \
  -v $(realpath ${REPO_PATH}):${CONTAINER_REPO_PATH} \
  -v $(realpath ${OUT_PATH}):${CONTAINER_OUT_PATH} cisa:latest \
  ${CISA_ROOT}/cisa/cisa \
  ${CONTAINER_REPO_PATH} ${ARGS} \
  -o ${CONTAINER_OUT_PATH} -x ${CONTAINER_RECONF_PATH}
